/*
SELECT CONCAT ('DROP TABLE ', table_name, ' CASCADE;') AS '--' FROM information_schema.tables WHERE table_schema = 'emarf' AND table_type = 'BASE TABLE'
UNION
SELECT CONCAT ('DROP VIEW ', table_name, ';') AS '--' FROM information_schema.views WHERE table_schema = 'emarf' 
*/
--
DROP TABLE m04_cd CASCADE;
DROP TABLE m04_id CASCADE;
DROP TABLE m04_idbn CASCADE;
DROP TABLE m04_no CASCADE;
DROP TABLE m05_ref1 CASCADE;
DROP TABLE m05_ref2 CASCADE;
DROP TABLE m05_ref3 CASCADE;
DROP TABLE mhr_busho CASCADE;
DROP TABLE mhr_shokui CASCADE;
DROP TABLE mhr_shokui_ninka CASCADE;
DROP TABLE mhr_user CASCADE;
DROP TABLE mhr_user_pos CASCADE;
DROP TABLE msy_kadobi CASCADE;
DROP TABLE msy_kbn CASCADE;
DROP TABLE msy_kbn_val CASCADE;
DROP TABLE msy_tax CASCADE;
DROP TABLE msy_tsuka CASCADE;
DROP TABLE t00_entity CASCADE;
DROP TABLE t00_nokey CASCADE;
DROP TABLE t01_dinks CASCADE;
DROP TABLE t01_ko CASCADE;
DROP TABLE t01_mago CASCADE;
DROP TABLE t01_orphan CASCADE;
DROP TABLE t01_oya CASCADE;
DROP TABLE t02_eldest CASCADE;
DROP TABLE t02_foster CASCADE;
DROP TABLE t02_younger CASCADE;
DROP TABLE t02_youngest CASCADE;
DROP TABLE t03_trans CASCADE;
DROP TABLE t03_trans_his CASCADE;
DROP TABLE t04_saiki CASCADE;
DROP TABLE t05_comp1 CASCADE;
DROP TABLE t05_comp2 CASCADE;
DROP TABLE t06_derive1 CASCADE;
DROP TABLE t06_derive1_det CASCADE;
DROP TABLE t06_derive2 CASCADE;
DROP TABLE t06_derive2_det CASCADE;
DROP TABLE t06_org CASCADE;
DROP TABLE t06_org_det CASCADE;
DROP TABLE t07_prev CASCADE;
DROP TABLE t07_prev_det CASCADE;
DROP TABLE t07_reborn CASCADE;
DROP TABLE t07_reborn_det CASCADE;
DROP TABLE t08_kisei1 CASCADE;
DROP TABLE t08_kisei2 CASCADE;
DROP TABLE t08_kyosei CASCADE;
DROP TABLE t09_grp1 CASCADE;
DROP TABLE t09_grp2 CASCADE;
DROP TABLE t09_sum CASCADE;
DROP TABLE t10_choice CASCADE;
DROP TABLE t10_koho1 CASCADE;
DROP TABLE t10_koho2 CASCADE;
DROP TABLE t11_prev2 CASCADE;
DROP TABLE t11_reborn2 CASCADE;
DROP TABLE t11_tasho1 CASCADE;
DROP TABLE t12_koho3 CASCADE;
DROP TABLE t12_reborn3 CASCADE;
DROP TABLE t12_tasho2 CASCADE;
DROP TABLE t13_dest CASCADE;
DROP TABLE t13_src CASCADE;
DROP VIEW v13_furiwake;
DROP VIEW v13_henkan;
