/*
SELECT 'DROP TABLE ' || table_name || ' PURGE;' AS "--" FROM user_tables 
UNION
SELECT 'DROP VIEW ' || view_name || ';' AS "--" FROM user_views 
*/
--
DROP TABLE MHR_BUSHO PURGE;
DROP TABLE MHR_SHOKUI PURGE;
DROP TABLE MHR_SHOKUI_NINKA PURGE;
DROP TABLE MHR_USER PURGE;
DROP TABLE MHR_USER_POS PURGE;
DROP TABLE MSY_KADOBI PURGE;
DROP TABLE MSY_KBN PURGE;
DROP TABLE MSY_KBN_VAL PURGE;
DROP TABLE MSY_TAX PURGE;
DROP TABLE MSY_TSUKA PURGE;
DROP TABLE TB0_NOKEY PURGE;
DROP TABLE TB1_CDREF PURGE;
DROP TABLE TB1_COMBO1 PURGE;
DROP TABLE TB1_COMBO2 PURGE;
DROP TABLE TB1_IDBN PURGE;
DROP TABLE TB1_IDREF PURGE;
DROP TABLE TB1_NOREF PURGE;
DROP TABLE TB1_REFER1 PURGE;
DROP TABLE TB1_REFER2 PURGE;
DROP TABLE TB1_REFER3 PURGE;
DROP TABLE TB1_SAIKI PURGE;
DROP TABLE TB2_ELDEST PURGE;
DROP TABLE TB2_FOSTER PURGE;
DROP TABLE TB2_YOUNGER PURGE;
DROP TABLE TB2_YOUNGEST PURGE;
DROP TABLE TB3_BEGIN PURGE;
DROP TABLE TB3_BEGIN_HIS PURGE;
DROP TABLE TB4_KO PURGE;
DROP TABLE TB4_KO_DINKS PURGE;
DROP TABLE TB4_KO_ORPHANS PURGE;
DROP TABLE TB4_MAGO PURGE;
DROP TABLE TB4_OYA PURGE;
DROP TABLE TB5_DERIVE PURGE;
DROP TABLE TB5_MERGE PURGE;
DROP TABLE TB5_PREV PURGE;
DROP TABLE TB5_PREV_DET PURGE;
DROP TABLE TB5_REBORN PURGE;
DROP TABLE TB5_REBORN_DET PURGE;
DROP TABLE TB6_DERIVE1 PURGE;
DROP TABLE TB6_DERIVE1_DET PURGE;
DROP TABLE TB6_DERIVE2 PURGE;
DROP TABLE TB6_DERIVE2_DET PURGE;
DROP TABLE TB6_ORG PURGE;
DROP TABLE TB6_ORG_DET PURGE;
DROP TABLE TB7_SUM PURGE;
DROP TABLE TB7_UNIT1 PURGE;
DROP TABLE TB7_UNIT2 PURGE;
DROP TABLE TB8_CHOICE PURGE;
DROP TABLE TB8_PREV2 PURGE;
DROP TABLE TB8_REBORN2 PURGE;
DROP TABLE TB8_SUM2 PURGE;
DROP TABLE TB8_SUM3 PURGE;
DROP TABLE TB8_UNIT3 PURGE;
DROP TABLE TB8_UNIT4 PURGE;
DROP TABLE TB9_DEST PURGE;
DROP TABLE TB9_SRC PURGE;
DROP TABLE TB0_ENTITY PURGE;
DROP VIEW TB9_FURIWAKE;
DROP VIEW TB9_HENKAN;
