/*
SELECT 'DROP TABLE ' || table_name || ' PURGE;' AS "--" FROM user_tables 
UNION
SELECT 'DROP VIEW ' || view_name || ';' AS "--" FROM user_views 
*/
--
DROP TABLE M04_CD PURGE;
DROP TABLE M04_ID PURGE;
DROP TABLE M04_IDBN PURGE;
DROP TABLE M04_NO PURGE;
DROP TABLE M04_SAIKI PURGE;
DROP TABLE M05_REF1 PURGE;
DROP TABLE M05_REF2 PURGE;
DROP TABLE M05_REF3 PURGE;
DROP TABLE MHR_BUSHO PURGE;
DROP TABLE MHR_SHOKUI PURGE;
DROP TABLE MHR_SHOKUI_NINKA PURGE;
DROP TABLE MHR_USER PURGE;
DROP TABLE MHR_USER_POS PURGE;
DROP TABLE MSY_KADOBI PURGE;
DROP TABLE MSY_KBN PURGE;
DROP TABLE MSY_KBN_VAL PURGE;
DROP TABLE MSY_TAX PURGE;
DROP TABLE MSY_TSUKA PURGE;
DROP TABLE T00_ENTITY PURGE;
DROP TABLE T00_NOKEY PURGE;
DROP TABLE T01_DINKS PURGE;
DROP TABLE T01_KO PURGE;
DROP TABLE T01_MAGO PURGE;
DROP TABLE T01_ORPHAN PURGE;
DROP TABLE T01_OYA PURGE;
DROP TABLE T02_ELDEST PURGE;
DROP TABLE T02_FOSTER PURGE;
DROP TABLE T02_YOUNGER PURGE;
DROP TABLE T02_YOUNGEST PURGE;
DROP TABLE T03_TRANS PURGE;
DROP TABLE T03_TRANS_HIS PURGE;
DROP TABLE T05_COMP1 PURGE;
DROP TABLE T05_COMP2 PURGE;
DROP TABLE T06_DERIVE1 PURGE;
DROP TABLE T06_DERIVE1_DET PURGE;
DROP TABLE T06_DERIVE2 PURGE;
DROP TABLE T06_DERIVE2_DET PURGE;
DROP TABLE T06_ORG PURGE;
DROP TABLE T06_ORG_DET PURGE;
DROP TABLE T07_PREV PURGE;
DROP TABLE T07_PREV_DET PURGE;
DROP TABLE T07_REBORN PURGE;
DROP TABLE T07_REBORN_DET PURGE;
DROP TABLE T08_KISEI1 PURGE;
DROP TABLE T08_KISEI2 PURGE;
DROP TABLE T08_KYOSEI PURGE;
DROP TABLE T09_GRP1 PURGE;
DROP TABLE T09_GRP2 PURGE;
DROP TABLE T09_SUM PURGE;
DROP TABLE T10_CHOICE PURGE;
DROP TABLE T10_KOHO1 PURGE;
DROP TABLE T10_KOHO2 PURGE;
DROP TABLE T11_PREV2 PURGE;
DROP TABLE T11_REBORN2 PURGE;
DROP TABLE T11_TASHO1 PURGE;
DROP TABLE T12_KOHO3 PURGE;
DROP TABLE T12_REBORN3 PURGE;
DROP TABLE T12_TASHO2 PURGE;
DROP TABLE T13_DEST PURGE;
DROP TABLE T13_SRC PURGE;
DROP VIEW V13_FURIWAKE;
DROP VIEW V13_HENKAN;
